//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmugMug.SendToSmugMug.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlbumPublic {
            get {
                return ((bool)(this["AlbumPublic"]));
            }
            set {
                this["AlbumPublic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlbumWorldSearchable {
            get {
                return ((bool)(this["AlbumWorldSearchable"]));
            }
            set {
                this["AlbumWorldSearchable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlbumSmugSearchable {
            get {
                return ((bool)(this["AlbumSmugSearchable"]));
            }
            set {
                this["AlbumSmugSearchable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlbumAllowExternalLinks {
            get {
                return ((bool)(this["AlbumAllowExternalLinks"]));
            }
            set {
                this["AlbumAllowExternalLinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlbumProtected {
            get {
                return ((bool)(this["AlbumProtected"]));
            }
            set {
                this["AlbumProtected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ApplyWatermark {
            get {
                return ((bool)(this["ApplyWatermark"]));
            }
            set {
                this["ApplyWatermark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlbmHideOwner {
            get {
                return ((bool)(this["AlbmHideOwner"]));
            }
            set {
                this["AlbmHideOwner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlbumDisplayCustomHeader {
            get {
                return ((bool)(this["AlbumDisplayCustomHeader"]));
            }
            set {
                this["AlbumDisplayCustomHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlbumCleanStyle {
            get {
                return ((bool)(this["AlbumCleanStyle"]));
            }
            set {
                this["AlbumCleanStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlbumShowCameraInfo {
            get {
                return ((bool)(this["AlbumShowCameraInfo"]));
            }
            set {
                this["AlbumShowCameraInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlbumShowFilenames {
            get {
                return ((bool)(this["AlbumShowFilenames"]));
            }
            set {
                this["AlbumShowFilenames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlbumGeography {
            get {
                return ((bool)(this["AlbumGeography"]));
            }
            set {
                this["AlbumGeography"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlbumSquareThumbs {
            get {
                return ((bool)(this["AlbumSquareThumbs"]));
            }
            set {
                this["AlbumSquareThumbs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlbumPhotoRank {
            get {
                return ((bool)(this["AlbumPhotoRank"]));
            }
            set {
                this["AlbumPhotoRank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlbumFriendEdit {
            get {
                return ((bool)(this["AlbumFriendEdit"]));
            }
            set {
                this["AlbumFriendEdit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlbumFamilyEdit {
            get {
                return ((bool)(this["AlbumFamilyEdit"]));
            }
            set {
                this["AlbumFamilyEdit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlbumAllowComments {
            get {
                return ((bool)(this["AlbumAllowComments"]));
            }
            set {
                this["AlbumAllowComments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlbumAllowEasySharing {
            get {
                return ((bool)(this["AlbumAllowEasySharing"]));
            }
            set {
                this["AlbumAllowEasySharing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlbumAllowPrintOrdering {
            get {
                return ((bool)(this["AlbumAllowPrintOrdering"]));
            }
            set {
                this["AlbumAllowPrintOrdering"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal AlbumPosition {
            get {
                return ((decimal)(this["AlbumPosition"]));
            }
            set {
                this["AlbumPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlbumSortDirection {
            get {
                return ((bool)(this["AlbumSortDirection"]));
            }
            set {
                this["AlbumSortDirection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MenuItemUploaded {
            get {
                return ((bool)(this["MenuItemUploaded"]));
            }
            set {
                this["MenuItemUploaded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MenuItemRatingUnrated {
            get {
                return ((bool)(this["MenuItemRatingUnrated"]));
            }
            set {
                this["MenuItemRatingUnrated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MenuItemRating1 {
            get {
                return ((bool)(this["MenuItemRating1"]));
            }
            set {
                this["MenuItemRating1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MenuItemRating2 {
            get {
                return ((bool)(this["MenuItemRating2"]));
            }
            set {
                this["MenuItemRating2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MenuItemRating3 {
            get {
                return ((bool)(this["MenuItemRating3"]));
            }
            set {
                this["MenuItemRating3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MenuItemRating4 {
            get {
                return ((bool)(this["MenuItemRating4"]));
            }
            set {
                this["MenuItemRating4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MenuItemRating5 {
            get {
                return ((bool)(this["MenuItemRating5"]));
            }
            set {
                this["MenuItemRating5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeSettings {
            get {
                return ((bool)(this["UpgradeSettings"]));
            }
            set {
                this["UpgradeSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int AlbumSorting {
            get {
                return ((int)(this["AlbumSorting"]));
            }
            set {
                this["AlbumSorting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SmugMug.Toolkit.Accounts Accounts {
            get {
                return ((global::SmugMug.Toolkit.Accounts)(this["Accounts"]));
            }
            set {
                this["Accounts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AlbumLargestSize {
            get {
                return ((int)(this["AlbumLargestSize"]));
            }
            set {
                this["AlbumLargestSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoadImagesFromSubfolders {
            get {
                return ((bool)(this["LoadImagesFromSubfolders"]));
            }
            set {
                this["LoadImagesFromSubfolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Duplicates {
            get {
                return ((int)(this["Duplicates"]));
            }
            set {
                this["Duplicates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultCategoryID {
            get {
                return ((int)(this["DefaultCategoryID"]));
            }
            set {
                this["DefaultCategoryID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.jpg</string>
  <string>.jpeg</string>
  <string>.png</string>
  <string>.gif</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PhotoExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PhotoExtensions"]));
            }
            set {
                this["PhotoExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.wmv</string>
  <string>.avi</string>
  <string>.mpg</string>
  <string>.mpeg</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection VideoExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VideoExtensions"]));
            }
            set {
                this["VideoExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.mov</string>
  <string>.qt</string>
  <string>.mp4</string>
  <string>.mqv</string>
  <string>.m4v</string>
  <string>.mqt</string>
  <string>.m2t</string>
  <string>.m2ts</string>
  <string>.mts</string>
  <string>.3gp</string>
  <string>.3gpp</string>
  <string>.3gp2</string>
  <string>.3g2</string>
  <string>.3gpp2</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection QuickTimeExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["QuickTimeExtensions"]));
            }
            set {
                this["QuickTimeExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlbumUnlisted {
            get {
                return ((bool)(this["AlbumUnlisted"]));
            }
            set {
                this["AlbumUnlisted"] = value;
            }
        }
    }
}
